### ISSUE TITLE
facts() is deprecated; use individual fact properties

### ISSUE THREAD

**Issue by pinggit** [networktocode/pyntc#212]
```
[ins] In [134]: sw1.facts()                                                                   
/usr/local/lib/python3.8/dist-packages/pyntc/devices/base_device.py:208: DeprecationWarning: f
acts() is deprecated; use individual fact properties.
  warnings.warn("facts() is deprecated; use individual fact properties.", DeprecationWarning)
```

how to get the facts now?

**Comment by jmcgill298** [comment]
each fact is its own property now.

dev = ntc_device(**kwargs)
dev.vendor
'cisco'
dev.hostname
'host1'

The available properties are:
* vendor
* hostname
* uptime
* uptime_string
* hostname
* fqdn
* interfaces
* vlans
* model
* serial_number
* os_version
* config_register (Cisco IOS only)
*

**Comment by pinggit** [comment]
got it. Thanks! 
Just wondering what's wrong to have an aggregated "facts" as before?

**Comment by jmcgill298** [comment]
1. You only have to wait for the information you want to load instead of waiting for everything to load
2. It is more python to have individual data attributes than to have a large dictionary of data
3. It is nicer to have attribute access than dictionary lookup (dot notation, obj.attr vs obj["attr"]
